Update bootstrap0

diff --git a/bootstrap0 b/bootstrap0
--- a/bootstrap0
+++ b/bootstrap0
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# version 1.1.1
+# version 1.1.2
 # Author: Steve Magnuson, AG7GN
 #
 # This script prepares the stock "Raspberry Pi OS with desktop" Bullseye image from 
@@ -66,8 +66,12 @@ function CheckInternet() {
 #######################################################################
 ## Determine OS
 eval $(cat /etc/*-release)
-[[ ${VERSION_CODENAME^^} != "BULLSEYE" ]] && \
-	{ echo >&2 "This script will only run with RaspiOS \"Bullseye\" OS"; exit 1; }
+if [[ ${VERSION_CODENAME^^} != "BULLSEYE" ]]
+then
+	echo >&2 -e "\033[1;33;41;5mERROR! ERROR! ERROR! \033[0m\033[1;33m This script will only run with RaspiOS \"Bullseye\" OS! \033[0m"
+	echo >&2 -e "\n\033[1;33mPlease follow the directions in the Wiki at https://github.com/NexusDR-X/nexus-bootstrap/wiki \033[0m\n"
+	exit 1
+fi
 OS_BITS=$(getconf LONG_BIT)
 echo >&2 "------>  Found Bullseye ${OS_BITS}-bit Operating System"
 
