Add diagnostics to bootstrap0

diff --git a/bootstrap0 b/bootstrap0
--- a/bootstrap0
+++ b/bootstrap0
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# version 1.1.2
+# version 1.1.3
 # Author: Steve Magnuson, AG7GN
 #
 # This script prepares the stock "Raspberry Pi OS with desktop" Bullseye image from 
@@ -18,6 +18,13 @@ NEXUS_UTILS_GIT_URL="https://github.com/NexusDR-X/nexus-utils"
 NEXUS_BOOTSTRAP_GIT_URL="${GIT_URL}/NexusDR-X/nexus-bootstrap.git"
 AUTOSTART="/etc/xdg/lxsession/LXDE-pi/autostart"
 NEXUS_VERSION="20220101.3"
+
+
+function Error () {
+	echo >&2 ">>>> FAILED: $1"
+	echo >&2 "Bootstrap 1 of 2 DID NOT complete!"
+	exit 1
+}
 
 #function bootAndRunAgain () {
 #	if [[ -s $AUTOSTART ]] 
@@ -78,11 +85,11 @@ echo >&2 "------>  Found Bullseye ${OS_BITS}-bit Operating System"
 #######################################################################
 ## Make the documentation and src directories.
 echo >&2 "------>  Make various folders..."
-sudo mkdir -p /usr/local/share/doc
-sudo mkdir -p /usr/local/share/applications
-sudo mkdir -p /usr/local/share/nexus
-sudo chown $USER:$USER /usr/local/share/nexus
-mkdir -p $HOME/.config/nexus
+sudo mkdir -p /usr/local/share/doc || Error "Could not create /usr/local/share/doc"
+sudo mkdir -p /usr/local/share/applications || Error "Could not create /usr/local/share/applications"
+sudo mkdir -p /usr/local/share/nexus || Error "Could not create /usr/local/share/nexus"
+sudo chown $USER:$USER /usr/local/share/nexus || Error "Could not chown $USER:$USER /usr/local/share/nexus"
+mkdir -p $HOME/.config/nexus || Error "Could not create $HOME/.config/nexus"
 echo >&2 -e "------>  Done.\n______"
 
 #######################################################################
@@ -90,7 +97,7 @@ echo >&2 -e "------>  Done.\n______"
 echo >&2 "------>  Enable sources..."
 for F in /etc/apt/sources.list /etc/apt/sources.list.d/raspi.list
 do
-	sudo sed -i -e 's/^#deb-src/deb-src/' $F
+	sudo sed -i -e 's/^#deb-src/deb-src/' $F || Error "Could not enable sources"
 done
 echo >&2 -e "------>  Done.\n______"
 
@@ -99,14 +106,14 @@ echo >&2 -e "------>  Done.\n______"
 for I in do_i2c do_serial do_ssh do_vnc
 do
 	echo >&2 "------>  Enable ${I##*_}..."
-	sudo raspi-config nonint $I 0
+	sudo raspi-config nonint $I 0 || Error "Could not enable $I"
 	echo >&2 -e "------>  Done.\n______"
 done
 
 #######################################################################
 ## Disable Screen Blanking
 echo >&2 "------>  Disable screen blanking..."
-sudo raspi-config nonint do_blanking 1
+sudo raspi-config nonint do_blanking 1 || Error "Could not disable screen blanking"
 echo >&2 -e "------>  Done.\n______"
 
 #######################################################################
@@ -114,7 +121,7 @@ echo >&2 -e "------>  Done.\n______"
 echo >&2 "------>  Set VNC resolution..."
 #sudo raspi-config nonint do_vnc_resolution "1280x720"
 #sudo raspi-config nonint do_vnc_resolution "800x600"
-sudo raspi-config nonint do_vnc_resolution "1920x1080"
+sudo raspi-config nonint do_vnc_resolution "1920x1080" || Error "Could not set VNC resolution"
 echo >&2 -e "------>  Done.\n______"
 
 #######################################################################
@@ -128,7 +135,7 @@ GEOMETRY_ROWS=30
 sed -i -e "s/^fontname=.*/fontname=$FONT/" \
 		-e "s/^scrollback=.*/scrollback=$SCROLLBACK/" \
 		-e "s/^geometry_columns=.*/geometry_columns=$GEOMETRY_COLUMNS/" \
-		-e "s/^geometry_rows=.*/geometry_rows=$GEOMETRY_ROWS/" "$CONFIG"
+		-e "s/^geometry_rows=.*/geometry_rows=$GEOMETRY_ROWS/" "$CONFIG" || Error "Could not set lxterminal settings"
 echo >&2 -e "------>  Done.\n______"
 
 #######################################################################
@@ -153,8 +160,8 @@ KEY_PATH="/usr/share/keyrings/nexus-archive-keyring.gpg"
 #curl -s --compressed "${GITHUBIO_REPO_URL}/KEY.gpg" | sudo apt-key add -
 #sudo curl -s --compressed -o /etc/apt/sources.list.d/nexus.list #"${GITHUBIO_REPO_URL}/nexus.list"
 # Here's the new way to add an apt repo and key:
-curl -s --compressed "${GITHUBIO_REPO_URL}/KEY.gpg" | sudo gpg --dearmor | sudo tee ${KEY_PATH} 1>/dev/null
-curl -s -o /tmp/${NEXUS_LIST} ${GITHUBIO_REPO_URL}/${NEXUS_LIST}
+curl -s --compressed "${GITHUBIO_REPO_URL}/KEY.gpg" | sudo gpg --dearmor | sudo tee ${KEY_PATH} 1>/dev/null || Error "Failed to get Nexus DR-X repo key"
+curl -s -o /tmp/${NEXUS_LIST} ${GITHUBIO_REPO_URL}/${NEXUS_LIST} || Error "Failed to get Nexus Dr-X repo URL"
 sed -i -e "s|^deb |deb [signed-by=${KEY_PATH}] |" /tmp/${NEXUS_LIST}
 sudo mv -f /tmp/${NEXUS_LIST} /etc/apt/sources.list.d/
 cat > /tmp/99nexus << EOF
@@ -169,12 +176,12 @@ echo >&2 -e "------>  Done.\n______"
 #######################################################################
 ## Update installed packages
 echo >&2 "------>  Update installed OS and packages..."
-sudo apt-get -y clean
-sudo apt-get update
-sudo apt-get -y autoremove
-sudo apt-get -y upgrade	
-sudo apt-get -y dist-upgrade
-sudo apt-get -y autoremove
+sudo apt-get -y clean || Error "apt-get clean failed"
+sudo apt-get update || Error "apt-get update failed"
+sudo apt-get -y autoremove || Error "apt-get autoremove failed"
+sudo apt-get -y upgrade	|| Error "apt-get upgrade failed"
+sudo apt-get -y dist-upgrade || Error "apt-get dist-upgrade failed"
+sudo apt-get -y autoremove || Error "apt-get autoremove failed"
 echo >&2 -e "------>  Done.\n______"
 
 #######################################################################
@@ -184,7 +191,7 @@ sudo apt-get -y install vim tcpdump lsof gpm telnet minicom links exfatprogs \
 		yad dosfstools dos2unix autoconf automake libtool cmake \
 		extra-xdg-menus bc dnsutils libgtk-3-bin jq xdotool moreutils build-essential \
 		aptitude hdparm watchdog gettext git imagemagick socat intltool libgtk-3-dev \
-		autotools-dev
+		autotools-dev || Error "Could not install additional packages"
 echo >&2 -e "------>  Done.\n______"
 
 #######################################################################
@@ -207,7 +214,7 @@ echo >&2 -e "------>  Done.\n______"
 ## Exclude Avahi traffic from ax interfaces
 echo >&2 "------>  Exclude Avahi traffic from ax25 interfaces..."
 sudo cp /etc/avahi/avahi-daemon.conf /etc/avahi/avahi-daemon.conf.original
-sudo sed -i -e "s/^#deny-interfaces=.*/deny-interfaces=ax0,ax1/" /etc/avahi/avahi-daemon.conf
+sudo sed -i -e "s/^#deny-interfaces=.*/deny-interfaces=ax0,ax1/" /etc/avahi/avahi-daemon.conf || Error "Could not modify /etc/avahi/avahi-daemon.conf"
 sudo systemctl restart avahi-daemon
 echo >&2 -e "------>  Done.\n______"
 
@@ -216,11 +223,11 @@ echo >&2 -e "------>  Done.\n______"
 echo >&2 "------>  Move /tmp and /var/log to RAM..."
 if ! grep -q -e "^tmpfs.*/tmp" /etc/fstab
 then
-	echo -e "tmpfs\t/tmp\ttmpfs\tdefaults,noatime,mode=1777,size=50m\t0\t0" | sudo tee --append /etc/fstab 1>/dev/null
+	echo -e "tmpfs\t/tmp\ttmpfs\tdefaults,noatime,mode=1777,size=50m\t0\t0" | sudo tee --append /etc/fstab 1>/dev/null || Error "Error creating /tmp RAM disk"
 fi
 if ! grep -q -e "^tmpfs.*/var/log" /etc/fstab
 then
-	echo -e "tmpfs\t/var/log\ttmpfs\tdefaults,noatime,mode=0755,size=50m\t0\t0" | sudo tee --append /etc/fstab 1>/dev/null
+	echo -e "tmpfs\t/var/log\ttmpfs\tdefaults,noatime,mode=0755,size=50m\t0\t0" | sudo tee --append /etc/fstab 1>/dev/null || Error "Error creating /var/log RAM disk"
 fi
 echo >&2 -e "------>  Done.\n______"
 
@@ -237,13 +244,13 @@ echo >&2 "------>  Configure and enabling hardware watchdog timer..."
 sudo cp -f /etc/watchdog.conf /etc/watchdog.conf.original
 sudo sed -i -e "s/^#max-load-1[ \t].*/max-load-1 = 24/" \
 				-e "s/^#max-load-5[ \t].*/max-load-5 = 18/" \
-				-e "s/^#watchdog-device.*/watchdog-device = \/dev\/watchdog/" /etc/watchdog.conf
+				-e "s/^#watchdog-device.*/watchdog-device = \/dev\/watchdog/" /etc/watchdog.conf || Error "Error enabling hardware watchdog"
 if ! grep -q "^watchdog-timeout" /etc/watchdog.conf
 then
 	echo "watchdog-timeout = 15" | sudo tee --append /etc/watchdog.conf 1>/dev/null
 fi
 sudo systemctl enable watchdog
-sudo systemctl start watchdog.service
+sudo systemctl start watchdog.service || Error "Error enabling hardware watchdog"
 echo >&2 -e "------>  Done.\n______"
 
 #######################################################################
@@ -270,7 +277,7 @@ echo >&2 -e "------>  Done.\n______"
 echo >&2 "------>  Enable Real Time Clock module..."
 if ! grep -q "^dtoverlay=i2c-rtc,ds3231" /boot/config.txt
 then
-	echo -e "# Enable ds3231 Real Time Clock (RTC)\ndtoverlay=i2c-rtc,ds3231"  | sudo tee --append /boot/config.txt 1>/dev/null
+	echo -e "# Enable ds3231 Real Time Clock (RTC)\ndtoverlay=i2c-rtc,ds3231"  | sudo tee --append /boot/config.txt 1>/dev/null || Error "Error enabling real time clock"
 fi
 echo >&2 -e "------>  Done.\n______"
 
@@ -285,8 +292,8 @@ echo >&2 -e "------>  Done.\n______"
 #######################################################################
 ## Prepare local git repository folder
 echo >&2 "------>  Make local git repository root folder..."
-sudo mkdir -p "$LOCAL_GIT_REPO_ROOT"
-sudo  chown $USER:$USER "$LOCAL_GIT_REPO_ROOT"
+sudo mkdir -p "$LOCAL_GIT_REPO_ROOT" || Error "Error creating $LOCAL_GIT_REPO_ROOT"
+sudo chown $USER:$USER "$LOCAL_GIT_REPO_ROOT" || Error "Error running chown $USER:$USER $LOCAL_GIT_REPO_ROOT"
 git config --global pull.rebase false
 echo >&2 -e "------>  Done.\n______"
 
@@ -311,7 +318,7 @@ echo >&2 -e "------>  Done.\n______"
 ## Get the nexus-bootstrap repo
 echo >&2 "------>  Add nexus-bootstrap repo..."
 rm -rf "$LOCAL_GIT_REPO_ROOT/nexus-bootstrap"
-git -C "$LOCAL_GIT_REPO_ROOT" clone "$NEXUS_BOOTSTRAP_GIT_URL"
+git -C "$LOCAL_GIT_REPO_ROOT" clone "$NEXUS_BOOTSTRAP_GIT_URL" || Error "Error creating local bootstrap repo"
 sudo cp -f $LOCAL_GIT_REPO_ROOT/nexus-bootstrap/bootstrap* /usr/local/sbin/
 echo >&2 -e "------>  Done.\n______"
 
@@ -321,7 +328,7 @@ for R in nexus-update nexus-utils direwolf-utils rigctl-utils
 do
 	echo >&2 "------>  Add $R repo..."
 	rm -rf "$LOCAL_GIT_REPO_ROOT/$R"
-	git -C "$LOCAL_GIT_REPO_ROOT" clone "https://github.com/NexusDR-X/$R"
+	git -C "$LOCAL_GIT_REPO_ROOT" clone "https://github.com/NexusDR-X/$R" || Error "Error creating local nexus-utils repo"
 	pushd . >/dev/null
 	cd "$LOCAL_GIT_REPO_ROOT"
 	${R}/nexus-install
@@ -468,6 +475,8 @@ echo >&2 -e "------>  Done.\n______"
 #######################################################################
 ## Pause
 echo >&2 "------>  Rebooting in 7 seconds..."
+echo >&2 "------>  To ABORT the bootstrap process, press Ctrl-C. DO NOT do this unless instructed."
+echo >&2
 sleep 7
 
 #######################################################################
