Fix libax25 installer

diff --git a/bootstrap0 b/bootstrap0
--- a/bootstrap0
+++ b/bootstrap0
@@ -17,7 +17,7 @@ NEXUS_UPDATE_GIT_URL="https://github.com/NexusDR-X/nexus-update"
 NEXUS_UTILS_GIT_URL="https://github.com/NexusDR-X/nexus-utils"
 NEXUS_BOOTSTRAP_GIT_URL="${GIT_URL}/NexusDR-X/nexus-bootstrap.git"
 AUTOSTART="/etc/xdg/lxsession/LXDE-pi/autostart"
-NEXUS_VERSION="20220101.4"
+NEXUS_VERSION="20220101.5"
 
 
 function Error () {
@@ -202,6 +202,18 @@ sudo apt-get -y install vim tcpdump lsof gpm telnet minicom links exfatprogs \
 		extra-xdg-menus bc dnsutils libgtk-3-bin jq xdotool moreutils build-essential \
 		aptitude hdparm watchdog gettext git imagemagick socat intltool libgtk-3-dev \
 		autotools-dev || Error "Could not install additional packages"
+echo >&2 -e "------>  Done.\n______"
+
+#######################################################################
+## Immediately install libax25 because it requires a force install due
+## to it's sharing a header file with libc6
+echo>&2 "------> Force install libax25 due to conflict with libc6"
+pushd . >/dev/null
+cd $HOME
+apt download $APP
+popd >/dev/null
+sudo dpkg -i --force-overwrite $HOME/libax25_*.deb || Error "Error installing libax25"
+rm -f $HOME/libax25_*
 echo >&2 -e "------>  Done.\n______"
 
 #######################################################################
